"use strict";

/**
 * Simple questions dataset.
 * Each question: { id, text, category, choices: string[], correctIndex, explanation? }
 */

const questions = [
  {
    id: "q1",
    text: "What is the capital of France?",
    category: "Geography",
    choices: ["Berlin", "Madrid", "Paris", "Rome"],
    correctIndex: 2,
    explanation: "Paris is the capital and most populous city of France.",
  },
  {
    id: "q2",
    text: "Which planet is known as the Red Planet?",
    category: "Science",
    choices: ["Venus", "Mars", "Jupiter", "Mercury"],
    correctIndex: 1,
    explanation: "Mars appears reddish due to iron oxide on its surface.",
  },
  {
    id: "q3",
    text: 'Who wrote "To Kill a Mockingbird"?',
    category: "Literature",
    choices: [
      "Harper Lee",
      "Mark Twain",
      "Ernest Hemingway",
      "F. Scott Fitzgerald",
    ],
    correctIndex: 0,
  },
  {
    id: "q4",
    text: "What is the largest ocean on Earth?",
    category: "Geography",
    choices: [
      "Atlantic Ocean",
      "Indian Ocean",
      "Pacific Ocean",
      "Arctic Ocean",
    ],
    correctIndex: 2,
  },
  {
    id: "q5",
    text: "What does HTTP stand for?",
    category: "Technology",
    choices: [
      "HyperText Transfer Protocol",
      "High Transfer Text Protocol",
      "Hyperlink Transfer Protocol",
      "HyperText Transition Procedure",
    ],
    correctIndex: 0,
  },
  {
    id: "q6",
    text: "Which language runs in a web browser?",
    category: "Technology",
    choices: ["Java", "C", "Python", "JavaScript"],
    correctIndex: 3,
  },
  {
    id: "q7",
    text: "How many continents are there on Earth?",
    category: "Geography",
    choices: ["5", "6", "7", "8"],
    correctIndex: 2,
  },
  {
    id: "q8",
    text: "What is H2O commonly known as?",
    category: "Science",
    choices: ["Hydrogen Peroxide", "Salt", "Water", "Oxygen"],
    correctIndex: 2,
  },
  {
    id: "q9",
    text: "In computing, what does CPU stand for?",
    category: "Technology",
    choices: [
      "Central Processing Unit",
      "Computer Personal Unit",
      "Central Performance Utility",
      "Core Process Unit",
    ],
    correctIndex: 0,
  },
  {
    id: "q10",
    text: "Which country hosted the 2020 Summer Olympics (held in 2021)?",
    category: "Events",
    choices: ["China", "Brazil", "Japan", "UK"],
    correctIndex: 2,
  },
  {
    id: "q11",
    text: "Which gas do plants primarily absorb for photosynthesis?",
    category: "Science",
    choices: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Hydrogen"],
    correctIndex: 2,
  },
  {
    id: "q12",
    text: 'Which element has the chemical symbol "Au"?',
    category: "Science",
    choices: ["Silver", "Gold", "Iron", "Copper"],
    correctIndex: 1,
  },
  {
    id: "q13",
    text: "What is the square root of 144?",
    category: "Math",
    choices: ["10", "11", "12", "13"],
    correctIndex: 2,
  },
  {
    id: "q14",
    text: "Which artist painted the Mona Lisa?",
    category: "Art",
    choices: [
      "Leonardo da Vinci",
      "Vincent van Gogh",
      "Pablo Picasso",
      "Michelangelo",
    ],
    correctIndex: 0,
  },
  {
    id: "q15",
    text: "Which continent is the Sahara Desert located in?",
    category: "Geography",
    choices: ["Asia", "Africa", "Australia", "South America"],
    correctIndex: 1,
  },
  // Additional general trivia
  {
    id: "g1",
    text: "What is the largest continent by land area?",
    category: "Geography",
    choices: ["Africa", "Asia", "Europe", "North America"],
    correctIndex: 1,
  },
  {
    id: "g2",
    text: "In which year was the first iPhone released?",
    category: "Technology",
    choices: ["2005", "2007", "2008", "2010"],
    correctIndex: 1,
  },
  {
    id: "g3",
    text: "What is the chemical symbol for Sodium?",
    category: "Science",
    choices: ["S", "So", "Na", "Sn"],
    correctIndex: 2,
  },
  {
    id: "g4",
    text: "What is the fastest land animal?",
    category: "Nature",
    choices: ["Pronghorn", "Cheetah", "Lion", "Greyhound"],
    correctIndex: 1,
  },
  {
    id: "g5",
    text: 'Who wrote the novel "1984"?',
    category: "Literature",
    choices: ["Aldous Huxley", "George Orwell", "Ray Bradbury", "J.K. Rowling"],
    correctIndex: 1,
  },
  {
    id: "g6",
    text: "What is the largest mammal?",
    category: "Nature",
    choices: ["African Elephant", "Blue Whale", "Giraffe", "Hippopotamus"],
    correctIndex: 1,
  },
  {
    id: "g7",
    text: "What is the currency of Japan?",
    category: "Geography",
    choices: ["Won", "Yuan", "Yen", "Ringgit"],
    correctIndex: 2,
  },
  {
    id: "g8",
    text: 'Who painted "The Starry Night"?',
    category: "Art",
    choices: [
      "Claude Monet",
      "Vincent van Gogh",
      "Pablo Picasso",
      "Edvard Munch",
    ],
    correctIndex: 1,
  },
  {
    id: "g9",
    text: "Which is commonly considered the longest river in the world?",
    category: "Geography",
    choices: ["Amazon", "Nile", "Yangtze", "Mississippi"],
    correctIndex: 1,
    explanation:
      "Many sources list the Nile as slightly longer; measurements vary.",
  },
  {
    id: "g10",
    text: "What is the smallest prime number?",
    category: "Math",
    choices: ["1", "2", "3", "5"],
    correctIndex: 1,
  },
  {
    id: "g11",
    text: "Which metal is liquid at room temperature?",
    category: "Science",
    choices: ["Mercury", "Aluminum", "Silver", "Lead"],
    correctIndex: 0,
  },
  {
    id: "g12",
    text: "Who created the Python programming language?",
    category: "Technology",
    choices: [
      "Guido van Rossum",
      "Linus Torvalds",
      "James Gosling",
      "Bjarne Stroustrup",
    ],
    correctIndex: 0,
  },
  {
    id: "g13",
    text: "What is the highest mountain above sea level?",
    category: "Geography",
    choices: ["K2", "Kangchenjunga", "Mount Everest", "Lhotse"],
    correctIndex: 2,
  },
  {
    id: "g14",
    text: "What is the largest hot desert in the world?",
    category: "Geography",
    choices: ["Gobi", "Sahara", "Arabian", "Mojave"],
    correctIndex: 1,
  },
  {
    id: "g15",
    text: "Which country has the most time zones (including territories)?",
    category: "Geography",
    choices: ["Russia", "USA", "France", "Australia"],
    correctIndex: 2,
  },
  {
    id: "g16",
    text: 'Which city is nicknamed "The Big Apple"?',
    category: "Geography",
    choices: ["New York City", "Los Angeles", "Chicago", "San Francisco"],
    correctIndex: 0,
  },
  {
    id: "g17",
    text: "Which gas do humans primarily breathe in to survive?",
    category: "Science",
    choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Hydrogen"],
    correctIndex: 0,
    wrongHumor: "It makes one wonder how you lasted this long...",
  },
  {
    id: "g18",
    text: "Who developed the theory of relativity?",
    category: "Science",
    choices: ["Isaac Newton", "Albert Einstein", "Niels Bohr", "Marie Curie"],
    correctIndex: 1,
  },
  {
    id: "g19",
    text: "Which instrument has keys, pedals, and strings?",
    category: "Art",
    choices: ["Violin", "Flute", "Piano", "Trumpet"],
    correctIndex: 2,
  },
  {
    id: "g20",
    text: "Which company created the Android operating system?",
    category: "Technology",
    choices: ["Apple", "Microsoft", "Google", "IBM"],
    correctIndex: 2,
  },
  {
    id: "g21",
    text: "How many degrees are in a right angle?",
    category: "Math",
    choices: ["45", "60", "90", "180"],
    correctIndex: 2,
  },
  {
    id: "g22",
    text: "What is the hardest natural substance?",
    category: "Science",
    choices: ["Diamond", "Quartz", "Obsidian", "Granite"],
    correctIndex: 0,
  },
  {
    id: "g23",
    text: "Which country gifted the Statue of Liberty to the United States?",
    category: "Geography",
    choices: ["United Kingdom", "France", "Spain", "Italy"],
    correctIndex: 1,
  },
  {
    id: "g24",
    text: 'In which sport is the term "hat-trick" traditionally used for three wickets in three balls?',
    category: "Sports",
    choices: ["Soccer", "Ice Hockey", "Cricket", "Baseball"],
    correctIndex: 2,
    explanation:
      "A bowling hat-trick in cricket is three wickets in three consecutive deliveries.",
  },
  {
    id: "g25",
    text: "What is the boiling point of water at sea level (°C)?",
    category: "Science",
    choices: ["90°C", "95°C", "100°C", "110°C"],
    correctIndex: 2,
  },
  // Airline and aviation trivia
  {
    id: "air1",
    text: "What is the IATA airport code for Los Angeles International Airport?",
    category: "Aviation",
    choices: ["LAX", "LGA", "LAS", "LHR"],
    correctIndex: 0,
  },
  {
    id: "air2",
    text: "Which airline is a founding member of Star Alliance?",
    category: "Aviation",
    choices: ["Emirates", "Lufthansa", "Qatar Airways", "Etihad"],
    correctIndex: 1,
  },
  {
    id: "air3",
    text: "Which aircraft family is nicknamed the “Dreamliner”?",
    category: "Aviation",
    choices: ["Airbus A350", "Boeing 787", "Boeing 777", "Airbus A330"],
    correctIndex: 1,
  },
  {
    id: "air4",
    text: "Which airline uses the callsign “Speedbird”?",
    category: "Aviation",
    choices: ["British Airways", "Air France", "Qantas", "United Airlines"],
    correctIndex: 0,
  },
  {
    id: "air5",
    text: "What is the largest passenger airliner in service?",
    category: "Aviation",
    choices: [
      "Boeing 747-8",
      "Airbus A350-1000",
      "Airbus A380",
      "Boeing 777-300ER",
    ],
    correctIndex: 2,
  },
  {
    id: "air6",
    text: "Which airport is the primary hub for Emirates?",
    category: "Aviation",
    choices: ["Abu Dhabi (AUH)", "Doha (DOH)", "Dubai (DXB)", "Riyadh (RUH)"],
    correctIndex: 2,
  },
  {
    id: "air7",
    text: "Qantas is the flag carrier airline of which country?",
    category: "Aviation",
    choices: ["New Zealand", "Australia", "Canada", "South Africa"],
    correctIndex: 1,
  },
  {
    id: "air8",
    text: "What is the ICAO airline code for Delta Air Lines?",
    category: "Aviation",
    choices: ["DL", "DAL", "DA", "DLA"],
    correctIndex: 1,
  },
  {
    id: "air9",
    text: "What was the first commercial jet airliner?",
    category: "Aviation",
    choices: [
      "Boeing 707",
      "de Havilland Comet",
      "Douglas DC-8",
      "Sud Aviation Caravelle",
    ],
    correctIndex: 1,
  },
  {
    id: "air10",
    text: "What does IATA stand for?",
    category: "Aviation",
    choices: [
      "International Air Travel Association",
      "International Air Transport Association",
      "Intercontinental Aviation Trade Association",
      "International Airline Transit Authority",
    ],
    correctIndex: 1,
  },
  {
    id: "air11",
    text: "Which global alliance is American Airlines a member of?",
    category: "Aviation",
    choices: ["Star Alliance", "SkyTeam", "Oneworld", "Value Alliance"],
    correctIndex: 2,
  },
  {
    id: "air12",
    text: "Typical cruising altitude for long-haul flights is approximately:",
    category: "Aviation",
    choices: [
      "10,000–15,000 ft",
      "20,000–25,000 ft",
      "30,000–40,000 ft",
      "45,000–55,000 ft",
    ],
    correctIndex: 2,
  },
  {
    id: "air13",
    text: "Runway numbers are primarily based on which of the following?",
    category: "Aviation",
    choices: [
      "Length in meters",
      "Elevation in feet",
      "Magnetic heading",
      "Surface type",
    ],
    correctIndex: 2,
  },
  {
    id: "air14",
    text: "Which cockpit instrument directly indicates an aircraft’s airspeed?",
    category: "Aviation",
    choices: [
      "Altimeter",
      "Airspeed Indicator",
      "Attitude Indicator",
      "Vertical Speed Indicator",
    ],
    correctIndex: 1,
  },
  {
    id: "air15",
    text: "What is the official language used for international air traffic control communications?",
    category: "Aviation",
    choices: ["Spanish", "French", "English", "German"],
    correctIndex: 2,
  },
  {
    id: "air16",
    text: "What does ETOPS stand for in aviation certification?",
    category: "Aviation",
    choices: [
      "Extended-range Twin-engine Operational Performance Standards",
      "Engine Time On Power Systems",
      "European Transport Operations Performance Scheme",
      "Extended Transport Operations Planning System",
    ],
    correctIndex: 0,
  },
  {
    id: "air17",
    text: "Which airline has its primary hub at Atlanta (ATL)?",
    category: "Aviation",
    choices: [
      "American Airlines",
      "Delta Air Lines",
      "United Airlines",
      "Southwest Airlines",
    ],
    correctIndex: 1,
  },
  {
    id: "air18",
    text: "IATA airline codes are typically how many characters long?",
    category: "Aviation",
    choices: ["1", "2", "3", "4"],
    correctIndex: 1,
  },
  {
    id: "air19",
    text: 'Which aircraft is commonly nicknamed the "Triple Seven"?',
    category: "Aviation",
    choices: ["Boeing 727", "Boeing 737", "Boeing 777", "Boeing 787"],
    correctIndex: 2,
  },
  {
    id: "air20",
    text: "Which airline alliance is Delta Air Lines a member of?",
    category: "Aviation",
    choices: ["Star Alliance", "Oneworld", "SkyTeam", "Value Alliance"],
    correctIndex: 2,
  },
  {
    id: "air21",
    text: "What does ICAO stand for?",
    category: "Aviation",
    choices: [
      "International Civil Aviation Organization",
      "International Cargo and Airline Organization",
      "Intercontinental Civil Aviation Office",
      "International Council of Airline Operations",
    ],
    correctIndex: 0,
  },
  {
    id: "air22",
    text: "Which system provides both lateral and vertical guidance for landing approaches?",
    category: "Aviation",
    choices: ["VOR", "NDB", "ILS", "DME"],
    correctIndex: 2,
  },
  {
    id: "air23",
    text: 'In transatlantic operations, what does "NAT" stand for?',
    category: "Aviation",
    choices: [
      "North Atlantic Track",
      "North American Trajectory",
      "Navigation and Timing",
      "Northern Approach Transition",
    ],
    correctIndex: 0,
  },
  {
    id: "air24",
    text: "Which cabin class most commonly features lie-flat seats on long-haul flights?",
    category: "Aviation",
    choices: ["Economy", "Premium Economy", "Business Class", "Basic Economy"],
    correctIndex: 2,
  },
  {
    id: "air25",
    text: 'Which manufacturer brands some wingtip devices as "Sharklets"?',
    category: "Aviation",
    choices: ["Airbus", "Boeing", "Embraer", "Bombardier"],
    correctIndex: 0,
  },
  // Additional 100 questions
  {
    id: "n001",
    text: "Which chemical element has the symbol He?",
    category: "Science",
    choices: ["Hydrogen", "Helium", "Hafnium", "Holmium"],
    correctIndex: 1,
  },
  {
    id: "n002",
    text: "What is the capital of Canada?",
    category: "Geography",
    choices: ["Toronto", "Ottawa", "Vancouver", "Montreal"],
    correctIndex: 1,
  },
  {
    id: "n003",
    text: "Who painted the ceiling of the Sistine Chapel?",
    category: "Art",
    choices: ["Michelangelo", "Raphael", "Donatello", "Leonardo da Vinci"],
    correctIndex: 0,
  },
  {
    id: "n004",
    text: "What is the largest internal organ in the human body?",
    category: "Science",
    choices: ["Liver", "Lung", "Heart", "Kidney"],
    correctIndex: 0,
  },
  {
    id: "n005",
    text: "Which country is known as the Land of the Rising Sun?",
    category: "Geography",
    choices: ["China", "Japan", "South Korea", "Thailand"],
    correctIndex: 1,
  },
  {
    id: "n006",
    text: "What is the freezing point of water in Fahrenheit?",
    category: "Science",
    choices: ["0°F", "32°F", "100°F", "212°F"],
    correctIndex: 1,
  },
  {
    id: "n007",
    text: 'Who wrote "Pride and Prejudice"?',
    category: "Literature",
    choices: [
      "Jane Austen",
      "Emily Brontë",
      "Charlotte Brontë",
      "Mary Shelley",
    ],
    correctIndex: 0,
  },
  {
    id: "n008",
    text: "Which planet has the most moons?",
    category: "Space",
    choices: ["Saturn", "Jupiter", "Uranus", "Neptune"],
    correctIndex: 1,
  },
  {
    id: "n009",
    text: "Which sport uses the terms love, deuce, and ace?",
    category: "Sports",
    choices: ["Tennis", "Badminton", "Squash", "Table Tennis"],
    correctIndex: 0,
  },
  {
    id: "n010",
    text: "The Pythagorean theorem applies to which type of triangle?",
    category: "Math",
    choices: ["Isosceles", "Right", "Equilateral", "Scalene"],
    correctIndex: 1,
  },
  {
    id: "n011",
    text: "Which language has the most native speakers?",
    category: "Language",
    choices: ["English", "Mandarin Chinese", "Spanish", "Hindi"],
    correctIndex: 1,
  },
  {
    id: "n012",
    text: "What is the smallest country in the world?",
    category: "Geography",
    choices: ["Monaco", "Nauru", "Vatican City", "San Marino"],
    correctIndex: 2,
  },
  {
    id: "n013",
    text: "Which metal is most commonly used for electrical wiring?",
    category: "Technology",
    choices: ["Aluminum", "Copper", "Silver", "Gold"],
    correctIndex: 1,
  },
  {
    id: "n014",
    text: "In computing, what does RAM stand for?",
    category: "Technology",
    choices: [
      "Random Access Memory",
      "Readily Available Memory",
      "Rapid Access Module",
      "Read Access Module",
    ],
    correctIndex: 0,
  },
  {
    id: "n015",
    text: 'Which instrument is known as the "king of instruments"?',
    category: "Music",
    choices: ["Piano", "Organ", "Violin", "Trumpet"],
    correctIndex: 1,
  },
  {
    id: "n016",
    text: "What is the hardest rock?",
    category: "Science",
    choices: ["Granite", "Basalt", "Diamond", "Quartzite"],
    correctIndex: 2,
  },
  {
    id: "n017",
    text: "Which ocean lies between Africa and Australia?",
    category: "Geography",
    choices: [
      "Atlantic Ocean",
      "Pacific Ocean",
      "Indian Ocean",
      "Southern Ocean",
    ],
    correctIndex: 2,
  },
  {
    id: "n018",
    text: "Who discovered penicillin?",
    category: "History",
    choices: [
      "Alexander Fleming",
      "Louis Pasteur",
      "Edward Jenner",
      "Marie Curie",
    ],
    correctIndex: 0,
  },
  {
    id: "n019",
    text: "What is the tallest building in the world (as of mid-2020s)?",
    category: "Geography",
    choices: [
      "Shanghai Tower",
      "Burj Khalifa",
      "Merdeka 118",
      "One World Trade Center",
    ],
    correctIndex: 1,
  },
  {
    id: "n020",
    text: "In which year did the Titanic sink?",
    category: "History",
    choices: ["1910", "1912", "1914", "1920"],
    correctIndex: 1,
  },
  {
    id: "n021",
    text: "What is the main gas found in the air we breathe?",
    category: "Science",
    choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Argon"],
    correctIndex: 2,
  },
  {
    id: "n022",
    text: "Which continent is the Amazon rainforest primarily located in?",
    category: "Geography",
    choices: ["Africa", "South America", "Asia", "Australia"],
    correctIndex: 1,
  },
  {
    id: "n023",
    text: 'Which artist is known for the painting "Guernica"?',
    category: "Art",
    choices: ["Pablo Picasso", "Salvador Dalí", "Joan Miró", "Henri Matisse"],
    correctIndex: 0,
  },
  {
    id: "n024",
    text: "What is the chemical symbol for Potassium?",
    category: "Science",
    choices: ["Po", "K", "P", "Pt"],
    correctIndex: 1,
  },
  {
    id: "n025",
    text: "Which planet spins on its side relative to its orbit?",
    category: "Space",
    choices: ["Uranus", "Neptune", "Saturn", "Jupiter"],
    correctIndex: 0,
  },
  {
    id: "n026",
    text: 'Who wrote "The Odyssey"?',
    category: "Literature",
    choices: ["Homer", "Sophocles", "Virgil", "Euripides"],
    correctIndex: 0,
  },
  {
    id: "n027",
    text: "Which city hosted the 2012 Summer Olympics?",
    category: "Events",
    choices: ["Beijing", "London", "Rio de Janeiro", "Tokyo"],
    correctIndex: 1,
  },
  {
    id: "n028",
    text: "In soccer, how many players are on the field per team?",
    category: "Sports",
    choices: ["9", "10", "11", "12"],
    correctIndex: 2,
  },
  {
    id: "n029",
    text: "Which country invented paper?",
    category: "History",
    choices: ["Egypt", "China", "Greece", "India"],
    correctIndex: 1,
  },
  {
    id: "n030",
    text: "What is the currency of the United Kingdom?",
    category: "Geography",
    choices: ["Euro", "US Dollar", "Pound Sterling", "Swiss Franc"],
    correctIndex: 2,
  },
  {
    id: "n031",
    text: "Which gas makes up most of the Sun?",
    category: "Space",
    choices: ["Helium", "Hydrogen", "Oxygen", "Neon"],
    correctIndex: 1,
  },
  {
    id: "n032",
    text: "Which famous scientist formulated the laws of motion?",
    category: "Science",
    choices: [
      "Albert Einstein",
      "Isaac Newton",
      "Galileo Galilei",
      "Niels Bohr",
    ],
    correctIndex: 1,
  },
  {
    id: "n033",
    text: "Which Italian city is famous for its canals?",
    category: "Geography",
    choices: ["Rome", "Venice", "Florence", "Milan"],
    correctIndex: 1,
  },
  {
    id: "n034",
    text: "What is the largest bone in the human body?",
    category: "Science",
    choices: ["Femur", "Humerus", "Tibia", "Pelvis"],
    correctIndex: 0,
  },
  {
    id: "n035",
    text: "Which continent has the most countries?",
    category: "Geography",
    choices: ["Asia", "Africa", "Europe", "South America"],
    correctIndex: 1,
  },
  {
    id: "n036",
    text: 'Who composed the "Fifth Symphony"?',
    category: "Music",
    choices: ["Mozart", "Beethoven", "Bach", "Tchaikovsky"],
    correctIndex: 1,
  },
  {
    id: "n037",
    text: "What does DNA stand for?",
    category: "Science",
    choices: [
      "Deoxyribonucleic Acid",
      "Dinucleic Acid",
      "Deoxyribose Acid",
      "Dinitrogen Acid",
    ],
    correctIndex: 0,
  },
  {
    id: "n038",
    text: "Which river runs through Egypt?",
    category: "Geography",
    choices: ["Nile", "Tigris", "Euphrates", "Jordan"],
    correctIndex: 0,
  },
  {
    id: "n039",
    text: "Which planet is closest to the Sun?",
    category: "Space",
    choices: ["Venus", "Mercury", "Earth", "Mars"],
    correctIndex: 1,
  },
  {
    id: "n040",
    text: 'Who is the author of "The Catcher in the Rye"?',
    category: "Literature",
    choices: [
      "J.D. Salinger",
      "Ernest Hemingway",
      "F. Scott Fitzgerald",
      "John Steinbeck",
    ],
    correctIndex: 0,
  },
  {
    id: "n041",
    text: "Which ocean is the Bermuda Triangle in?",
    category: "Geography",
    choices: [
      "Indian Ocean",
      "Atlantic Ocean",
      "Pacific Ocean",
      "Arctic Ocean",
    ],
    correctIndex: 1,
  },
  {
    id: "n042",
    text: "What is 12 × 12?",
    category: "Math",
    choices: ["122", "124", "144", "132"],
    correctIndex: 2,
  },
  {
    id: "n043",
    text: "Which gas do plants release as a byproduct of photosynthesis?",
    category: "Science",
    choices: ["Oxygen", "Carbon Dioxide", "Nitrogen", "Methane"],
    correctIndex: 0,
  },
  {
    id: "n044",
    text: "Which country is home to the Great Barrier Reef?",
    category: "Geography",
    choices: ["Australia", "Indonesia", "Philippines", "New Zealand"],
    correctIndex: 0,
  },
  {
    id: "n045",
    text: 'Who painted "Girl with a Pearl Earring"?',
    category: "Art",
    choices: ["Vermeer", "Rembrandt", "Rubens", "Caravaggio"],
    correctIndex: 0,
  },
  {
    id: "n046",
    text: "What is the largest planet in our solar system?",
    category: "Space",
    choices: ["Jupiter", "Saturn", "Neptune", "Uranus"],
    correctIndex: 0,
  },
  {
    id: "n047",
    text: "In which sport would you perform a slam dunk?",
    category: "Sports",
    choices: ["Volleyball", "Basketball", "Tennis", "Rugby"],
    correctIndex: 1,
  },
  {
    id: "n048",
    text: "Which organ pumps blood throughout the body?",
    category: "Science",
    choices: ["Lungs", "Liver", "Heart", "Pancreas"],
    correctIndex: 2,
  },
  {
    id: "n049",
    text: "What is the capital of Spain?",
    category: "Geography",
    choices: ["Barcelona", "Madrid", "Seville", "Valencia"],
    correctIndex: 1,
  },
  {
    id: "n050",
    text: 'Who wrote "Moby-Dick"?',
    category: "Literature",
    choices: [
      "Herman Melville",
      "Mark Twain",
      "Nathaniel Hawthorne",
      "Edgar Allan Poe",
    ],
    correctIndex: 0,
  },
  {
    id: "n051",
    text: "Which country is famous for the Eiffel Tower?",
    category: "Geography",
    choices: ["Italy", "France", "Germany", "Spain"],
    correctIndex: 1,
  },
  {
    id: "n052",
    text: "What is the square root of 169?",
    category: "Math",
    choices: ["11", "12", "13", "14"],
    correctIndex: 2,
  },
  {
    id: "n053",
    text: "Which planet is known for its prominent rings?",
    category: "Space",
    choices: ["Jupiter", "Saturn", "Uranus", "Neptune"],
    correctIndex: 1,
  },
  {
    id: "n054",
    text: 'Who is known as the "Father of Computers"?',
    category: "Technology",
    choices: [
      "Alan Turing",
      "Bill Gates",
      "Charles Babbage",
      "John von Neumann",
    ],
    correctIndex: 2,
  },
  {
    id: "n055",
    text: "What is the chemical symbol for Silver?",
    category: "Science",
    choices: ["Si", "Ag", "Sr", "Au"],
    correctIndex: 1,
  },
  {
    id: "n056",
    text: "Which city is known as the Eternal City?",
    category: "Geography",
    choices: ["Athens", "Rome", "Istanbul", "Jerusalem"],
    correctIndex: 1,
  },
  {
    id: "n057",
    text: "How many stripes are on the US flag?",
    category: "History",
    choices: ["11", "12", "13", "14"],
    correctIndex: 2,
  },
  {
    id: "n058",
    text: 'Which composer wrote "The Four Seasons"?',
    category: "Music",
    choices: ["Bach", "Vivaldi", "Handel", "Haydn"],
    correctIndex: 1,
  },
  {
    id: "n059",
    text: "What is the process by which plants make food?",
    category: "Science",
    choices: ["Respiration", "Transpiration", "Photosynthesis", "Fermentation"],
    correctIndex: 2,
  },
  {
    id: "n060",
    text: "Which country has the city of Marrakech?",
    category: "Geography",
    choices: ["Spain", "Morocco", "Portugal", "Algeria"],
    correctIndex: 1,
  },
  {
    id: "n061",
    text: "Which artist cut off part of his own ear?",
    category: "Art",
    choices: ["Gauguin", "Van Gogh", "Cézanne", "Monet"],
    correctIndex: 1,
  },
  {
    id: "n062",
    text: "Which planet is called Earth’s twin?",
    category: "Space",
    choices: ["Mars", "Venus", "Mercury", "Neptune"],
    correctIndex: 1,
  },
  {
    id: "n063",
    text: "What is the chemical symbol for Carbon?",
    category: "Science",
    choices: ["Co", "C", "Ca", "Cb"],
    correctIndex: 1,
  },
  {
    id: "n064",
    text: 'Who wrote "The Great Gatsby"?',
    category: "Literature",
    choices: [
      "F. Scott Fitzgerald",
      "Ernest Hemingway",
      "William Faulkner",
      "John Steinbeck",
    ],
    correctIndex: 0,
  },
  {
    id: "n065",
    text: "What is the capital of Australia?",
    category: "Geography",
    choices: ["Sydney", "Melbourne", "Canberra", "Brisbane"],
    correctIndex: 2,
  },
  {
    id: "n066",
    text: "What is 9 × 7?",
    category: "Math",
    choices: ["56", "61", "63", "72"],
    correctIndex: 2,
  },
  {
    id: "n067",
    text: "Which metal has the chemical symbol Fe?",
    category: "Science",
    choices: ["Lead", "Iron", "Tin", "Zinc"],
    correctIndex: 1,
  },
  {
    id: "n068",
    text: "Which instrument has 47 strings and 7 pedals?",
    category: "Music",
    choices: ["Harp", "Piano", "Guitar", "Cello"],
    correctIndex: 0,
  },
  {
    id: "n069",
    text: "Which country is the origin of the Olympic Games?",
    category: "History",
    choices: ["Italy", "Greece", "Egypt", "Turkey"],
    correctIndex: 1,
  },
  {
    id: "n070",
    text: "What is the primary language spoken in Brazil?",
    category: "Language",
    choices: ["Spanish", "Portuguese", "French", "English"],
    correctIndex: 1,
  },
  {
    id: "n071",
    text: "Which desert covers much of northern Africa?",
    category: "Geography",
    choices: ["Gobi", "Sahara", "Kalahari", "Atacama"],
    correctIndex: 1,
  },
  {
    id: "n072",
    text: "Which natural satellite orbits Earth?",
    category: "Space",
    choices: ["Phobos", "Europa", "Moon", "Titan"],
    correctIndex: 2,
  },
  {
    id: "n073",
    text: "What is the chemical symbol for Sodium chloride?",
    category: "Science",
    choices: ["NaCl", "NaC", "NCl", "SCl"],
    correctIndex: 0,
  },
  {
    id: "n074",
    text: 'Who wrote "Hamlet"?',
    category: "Literature",
    choices: [
      "Christopher Marlowe",
      "William Shakespeare",
      "Ben Jonson",
      "John Donne",
    ],
    correctIndex: 1,
  },
  {
    id: "n075",
    text: "Which continent is Greenland associated with geographically?",
    category: "Geography",
    choices: ["North America", "Europe", "Asia", "Arctic"],
    correctIndex: 0,
  },
  {
    id: "n076",
    text: "What is the longest bone in the human arm?",
    category: "Science",
    choices: ["Radius", "Ulna", "Humerus", "Scapula"],
    correctIndex: 2,
  },
  {
    id: "n077",
    text: "Which country has the city of Kyoto?",
    category: "Geography",
    choices: ["China", "Japan", "South Korea", "Vietnam"],
    correctIndex: 1,
  },
  {
    id: "n078",
    text: "What is the value of Pi rounded to two decimal places?",
    category: "Math",
    choices: ["3.12", "3.14", "3.16", "3.18"],
    correctIndex: 1,
  },
  {
    id: "n079",
    text: "Which force keeps planets in orbit around the Sun?",
    category: "Science",
    choices: ["Magnetism", "Friction", "Gravity", "Inertia"],
    correctIndex: 2,
  },
  {
    id: "n080",
    text: "What is the capital of Egypt?",
    category: "Geography",
    choices: ["Alexandria", "Cairo", "Giza", "Luxor"],
    correctIndex: 1,
  },
  {
    id: "n081",
    text: "Which musician is known as the King of Pop?",
    category: "Music",
    choices: ["Elvis Presley", "Michael Jackson", "Prince", "Freddie Mercury"],
    correctIndex: 1,
  },
  {
    id: "n082",
    text: "Which planet has the Great Red Spot?",
    category: "Space",
    choices: ["Venus", "Mars", "Jupiter", "Saturn"],
    correctIndex: 2,
  },
  {
    id: "n083",
    text: "Which scientist is known for the three laws of planetary motion?",
    category: "Science",
    choices: ["Kepler", "Copernicus", "Galileo", "Tycho Brahe"],
    correctIndex: 0,
  },
  {
    id: "n084",
    text: "What is the capital of Argentina?",
    category: "Geography",
    choices: ["Buenos Aires", "Santiago", "Lima", "Montevideo"],
    correctIndex: 0,
  },
  {
    id: "n085",
    text: "Which language is primarily spoken in Austria?",
    category: "Language",
    choices: ["German", "Dutch", "French", "Italian"],
    correctIndex: 0,
  },
  {
    id: "n086",
    text: "Which number is a prime: 21, 23, 25, 27?",
    category: "Math",
    choices: ["21", "23", "25", "27"],
    correctIndex: 1,
  },
  {
    id: "n087",
    text: "What is the basic unit of life?",
    category: "Science",
    choices: ["Atom", "Molecule", "Cell", "Organ"],
    correctIndex: 2,
  },
  {
    id: "n088",
    text: "Which country is known for the Taj Mahal?",
    category: "Geography",
    choices: ["Pakistan", "India", "Bangladesh", "Nepal"],
    correctIndex: 1,
  },
  {
    id: "n089",
    text: 'Which artist painted "The Persistence of Memory"?',
    category: "Art",
    choices: ["Dalí", "Picasso", "Matisse", "Klee"],
    correctIndex: 0,
  },
  {
    id: "n090",
    text: "Which gas is essential for human respiration?",
    category: "Science",
    choices: ["Oxygen", "Nitrogen", "Carbon Dioxide", "Helium"],
    correctIndex: 0,
  },
  {
    id: "n091",
    text: "Which river flows through Paris?",
    category: "Geography",
    choices: ["Thames", "Seine", "Rhine", "Danube"],
    correctIndex: 1,
  },
  {
    id: "n092",
    text: "What is the largest land animal?",
    category: "Nature",
    choices: ["White Rhino", "Hippopotamus", "African Elephant", "Giraffe"],
    correctIndex: 2,
  },
  {
    id: "n093",
    text: "Which organ is responsible for filtering blood?",
    category: "Science",
    choices: ["Liver", "Kidney", "Spleen", "Pancreas"],
    correctIndex: 1,
  },
  {
    id: "n094",
    text: "Which is the smallest prime number greater than 100?",
    category: "Math",
    choices: ["101", "103", "107", "109"],
    correctIndex: 0,
  },
  {
    id: "n095",
    text: "What is the capital of Norway?",
    category: "Geography",
    choices: ["Oslo", "Bergen", "Stockholm", "Copenhagen"],
    correctIndex: 0,
  },
  {
    id: "n096",
    text: "What is the chemical symbol for Gold?",
    category: "Science",
    choices: ["Ag", "Au", "Gd", "Go"],
    correctIndex: 1,
  },
  {
    id: "n097",
    text: 'Who wrote "Crime and Punishment"?',
    category: "Literature",
    choices: ["Tolstoy", "Dostoevsky", "Chekhov", "Turgenev"],
    correctIndex: 1,
  },
  {
    id: "n098",
    text: "Which city is known as the City of Light?",
    category: "Geography",
    choices: ["Paris", "Prague", "Vienna", "Budapest"],
    correctIndex: 0,
  },
  {
    id: "n099",
    text: "Which planet is the hottest in the solar system?",
    category: "Space",
    choices: ["Mercury", "Venus", "Mars", "Earth"],
    correctIndex: 1,
  },
  {
    id: "n100",
    text: "Which country is known for the city of Machu Picchu?",
    category: "Geography",
    choices: ["Chile", "Peru", "Bolivia", "Ecuador"],
    correctIndex: 1,
  },
];

module.exports = { questions };
